### ISSUE TITLE
Metamask integration docs

### ISSUE THREAD

**Issue by Ruteri** [flashbots/suave-viem#26]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Package Version

1.14.0

### Current Behavior

Integrating with Metamask seems like a common use case, but I couldn't get it to work. If it should work, I think sample code for how to integrate with Metamask would be of great value.

**Comment by zeroXbrock** [comment]
maintaining an example here: https://github.com/zeroXbrock/web-suapp
